services:
  - type: web
    name: schooly-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-snowy-king-aopqgrht-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: APP_JWT_SECRET
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: validate
