spring.application.name=school-erp-backend
spring.datasource.url=jdbc:postgresql://dpg-d7fo3mmrnols73f6i3jg-a.oregon-postgres.render.com:5432/school_erp_db_8r8k
spring.datasource.username=school_erp_db_8r8k_user
spring.datasource.password=9KIkD2ZOnDzgEL1LmSqJZRlUmopI4CV8

#postgresql://school_erp_db_8r8k_user:9KIkD2ZOnDzgEL1LmSqJZRlUmopI4CV8@dpg-d7fo3mmrnols73f6i3jg-a.oregon-postgres.render.com/school_erp_db_8r8k
#spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=240000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-timeout=30000
server.port=${PORT:8080}
app.jwt.secret=change-me-change-me-change-me-change-me-change-me
app.jwt.access-token-expiration-ms=86400000
app.jwt.refresh-token-expiration-ms=604800000