ALTER TABLE exam_schedules
ADD COLUMN IF NOT EXISTS component_type VARCHAR(50) DEFAULT 'THEORY' NOT NULL;

ALTER TABLE exam_schedules
ALTER COLUMN status SET DEFAULT 'DRAFT';

ALTER TABLE exam_marks
ADD COLUMN IF NOT EXISTS component_type VARCHAR(50) DEFAULT 'THEORY' NOT NULL;
