-- V15__Add_Demographics_To_Entities.sql
-- Add fields to class, student, and staff to support the frontend UI schemas

-- 1. Class
ALTER TABLE class ADD COLUMN IF NOT EXISTS grade INT;
ALTER TABLE class ADD COLUMN IF NOT EXISTS level VARCHAR(50);
ALTER TABLE class ADD COLUMN IF NOT EXISTS section VARCHAR(50);

-- 2. Student (Demographics & Guardian)
ALTER TABLE student ADD COLUMN IF NOT EXISTS first_name VARCHAR(100);
ALTER TABLE student ADD COLUMN IF NOT EXISTS last_name VARCHAR(100);
ALTER TABLE student ADD COLUMN IF NOT EXISTS gender VARCHAR(20);
ALTER TABLE student ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE student ADD COLUMN IF NOT EXISTS blood_group VARCHAR(10);
ALTER TABLE student ADD COLUMN IF NOT EXISTS religion VARCHAR(50);
ALTER TABLE student ADD COLUMN IF NOT EXISTS nationality VARCHAR(50);
ALTER TABLE student ADD COLUMN IF NOT EXISTS previous_school VARCHAR(200);
ALTER TABLE student ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE student ADD COLUMN IF NOT EXISTS photo_url VARCHAR(255);

ALTER TABLE student ADD COLUMN IF NOT EXISTS guardian_name VARCHAR(100);
ALTER TABLE student ADD COLUMN IF NOT EXISTS guardian_relation VARCHAR(50);
ALTER TABLE student ADD COLUMN IF NOT EXISTS guardian_phone VARCHAR(20);
ALTER TABLE student ADD COLUMN IF NOT EXISTS guardian_email VARCHAR(100);
ALTER TABLE student ADD COLUMN IF NOT EXISTS guardian_occupation VARCHAR(100);

-- 3. Staff
ALTER TABLE staff ADD COLUMN IF NOT EXISTS first_name VARCHAR(100);
ALTER TABLE staff ADD COLUMN IF NOT EXISTS last_name VARCHAR(100);
ALTER TABLE staff ADD COLUMN IF NOT EXISTS department VARCHAR(100);
ALTER TABLE staff ADD COLUMN IF NOT EXISTS designation VARCHAR(100);
ALTER TABLE staff ADD COLUMN IF NOT EXISTS photo_url VARCHAR(255);
ALTER TABLE staff ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE staff ADD COLUMN IF NOT EXISTS email VARCHAR(100);
